[package]
name = "myjson"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2.1.1"
ryu = "1.0"

[dev-dependencies]
criterion = "0.6.0"
simd-json = "0.15.1"
serde_json = "1.0"

[[bench]]
name = "bench"
harness = false

[workspace]
resolver = "3"
members = ["example"]
